Include conf/common.conf
# Basic authentication only.
<Directory /data>
    Dav On
    Options Indexes
    AuthType Basic
    AuthName "rclone-test"
    AuthBasicProvider file
    AuthUserFile /usr/local/apache2/conf/basic.passwd
    Require valid-user
</Directory>
