Include conf/common.conf
<Directory /data>
    Dav On
    Options Indexes
    AuthType Digest
    AuthName "rclone-test"
    AuthDigestProvider file
    AuthUserFile /usr/local/apache2/conf/digest.passwd
    AuthDigestNonceLifetime 300
    Require valid-user
</Directory>
